### PR TITLE
added editor snippets links

### PR DESCRIPTION
**Pull request by capaj**

### CODE REVIEW

**Comment by Flet** [comment]
:+1:

**Comment by jprichardson** [comment]
Eeeks. While I don't mind people promoting my projects, my snippets are woefully incomplete ATM. I suppose I'll have to get on that :)

**Comment by feross** [comment]
@jprichardson :) this pr has been sitting here for a while, you had so much time!! ;) glad we finally got it merged.

**Comment by capaj** [comment]
@ferros thanks.

@jprichardson I think that the atom snippets are almost complete. Maybe you could get some ideas about missing snippets there?

**Pull request merged**
