### PR TITLE
add sstandard-sass

### PR DESCRIPTION
**Pull request by jetiny**
add standard-sass after standard section.

### CODE REVIEW

**Comment by feross** [comment]
Thanks for the PR. This isn't the right place in the readme for this. I'll move it to the right section.

**Comment by rstacruz** [comment]
btw, there's also https://www.npmjs.com/package/stylelint-config-standard which is what I use in most my projects. I personally prefer stylelint to sasslint.

**Comment by jetiny** [comment]
Standard-sass is a simple, zero-configuration, standalone(Independent) command-line sass(css) style linter (use sass-lint) like standard-js

The default `<sass-path-pattern>`
  include:
    - 's+(a|c)ss/**/*.s+(a|c)ss'
    - 'css/**/*.css'
  ignore:
    - 'node_modules'
    - 'dist'

May be you can have a try @rstacruz

**Comment by feross** [comment]
@rstacruz Thanks, will add it to the list

**Pull request merged**
